### ISSUE TITLE
Pourquoi "text="CONTACT" ?

### ISSUE THREAD

**Issue by AdrienLapasset** [clementlapasset/portfolio-clement-lapasset#4]
https://github.com/clementlapasset/portfolio-clement-lapasset/blob/9361c9b0155e6c257c8e6a5fe26e2969245515f9/src/components/sections/ContactSection/index.js#L9

**Comment by clementlapasset** [comment]
C'est pour la police custom en 3D, ça me permet de mettre des pseudo-elements qui remprennent le même texte avec une seule div.
