### ISSUE TITLE
Comment tu passes une props "text" à la div alors que ce n'est pas un composant ?

### ISSUE THREAD

**Issue by AdrienLapasset** [clementlapasset/portfolio-clement-lapasset#6]
https://github.com/clementlapasset/portfolio-clement-lapasset/blob/9361c9b0155e6c257c8e6a5fe26e2969245515f9/src/components/sections/HeroSection/index.js#L10

**Comment by clementlapasset** [comment]
C'est pour réutiliser l'attribut dans le CSS (pour utiliser plusieurs couches de police)

**Comment by AdrienLapasset** [comment]
Ah bah je savais pas que tu pouvais faire ça
