### ISSUE TITLE
il faut un <ul> sous le <li>

### ISSUE THREAD

**Issue by AdrienLapasset** [clementlapasset/portfolio-clement-lapasset#7]
https://github.com/clementlapasset/portfolio-clement-lapasset/blob/9361c9b0155e6c257c8e6a5fe26e2969245515f9/src/components/sections/ProjectSection/index.js#L49

**Comment by clementlapasset** [comment]
C'est-à-dire ? C'est pas le contraire `<ul><li></ul>` ?

**Comment by AdrienLapasset** [comment]
Oups je me suis trompé tu avais bien le `<ul><li>`
